import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9ff",
        "on-primary-fixed-variant": "#0040a2",
        "on-primary-fixed": "#001848",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d7e2ff",
        "secondary-fixed-dim": "#ffb781",
        "surface-bright": "#f9f9ff",
        "primary-fixed-dim": "#b2c5ff",
        outline: "#737685",
        "on-secondary-fixed-variant": "#6f3800",
        "surface-variant": "#d7e2ff",
        "secondary-fixed": "#ffdcc4",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#f1f3ff",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed": "#8df7c1",
        "secondary-container": "#f88400",
        "on-secondary-container": "#5b2d00",
        "inverse-primary": "#b2c5ff",
        "on-background": "#041b3c",
        "on-tertiary-fixed-variant": "#005235",
        secondary: "#924c00",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "primary-container": "#0052cc",
        "surface-dim": "#cadaff",
        "on-surface": "#041b3c",
        primary: "#003d9b",
        "on-secondary-fixed": "#2f1400",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#e0e8ff",
        "on-primary-container": "#c4d2ff",
        "tertiary-container": "#006844",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#71dba6",
        "surface-container": "#e8edff",
        error: "#ba1a1a",
        background: "#f9f9ff",
        tertiary: "#004e32",
        "on-error": "#ffffff",
        "inverse-surface": "#1d3052",
        "surface-tint": "#0c56d0",
        "primary-fixed": "#dae2ff",
        "on-tertiary-container": "#7de7b2",
        "on-surface-variant": "#434654",
      },
      fontFamily: {
        inter: ["var(--font-inter)"],
        space: ["var(--font-space-grotesk)"],
      },
      spacing: {
        md: "16px",
        xl: "32px",
        lg: "24px",
        xs: "4px",
        margin: "20px",
        gutter: "16px",
        sm: "8px",
        base: "4px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
} satisfies Config;
